# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MY_AI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1384, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Erica = QtWidgets.QLabel(self.centralwidget)
        self.Erica.setGeometry(QtCore.QRect(14, 10, 1361, 741))
        font = QtGui.QFont()
        font.setFamily("Wide Latin")
        self.Erica.setFont(font)
        self.Erica.setText("")
        self.Erica.setPixmap(QtGui.QPixmap("GUI/Graphics.gif"))
        self.Erica.setScaledContents(True)
        self.Erica.setObjectName("Erica")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(940, 620, 151, 81))
        self.pushButton.setStyleSheet("background-color: rgb(117, 161, 255);\n"
"font: 75 26pt \"Palatino Linotype\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1180, 620, 151, 81))
        self.pushButton_2.setStyleSheet("background-color: rgb(117, 161, 255);\n"
"font: 75 26pt \"Palatino Linotype\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 40, 191, 51))
        self.label.setStyleSheet("background: transparent;\n" "color: white;\n" "font: 75 18pt \"Palatino Linotype\";")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 40, 181, 51))
        self.label_2.setStyleSheet("background: transparent;\n" "color: white;\n" "font: 75 18pt \"Palatino Linotype\";")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "START"))
        self.pushButton_2.setText(_translate("MainWindow", "STOP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
